Update module language style
shwestrick/parse-sml pull request #35
Opened 2021-12-24 22:08 UTC by HarrisonGrodin

Known bugs:
- [ ] Sometimes eats comments, e.g.
```sml
structure S =
  struct
    val x = 3
    (* hi *)
  end
```
- [ ] (`include` followed by `sharing` moves `sharing` to `include` line; although, doesn't seem to be due to changes here)

2021-12-24 22:09 UTC, HarrisonGrodin reviewed
Not very confident in my changes to the doc structures (especially wrt the unchanged functions where `Rigid` hits `_`).

2021-12-24 22:09 UTC, HarrisonGrodin commented on src/base/PrettySimpleDoc.sml
> +        | Rigid d => (false, Rigid d, 0 (* TODO *), false)
Unsure what to put for the third component here; may be causing the comment eating?

2021-12-25 00:08 UTC, shwestrick commented
For the issue with eating comments, in function `TokenDoc.insertComments`, there are a couple inner functions that need cases for `Rigid`. See the `Group` and `Indent` cases -- I think the `Rigid` case should be similar.

2021-12-25 00:24 UTC, shwestrick requested changes
See also this comment: https://github.com/shwestrick/parse-sml/pull/35#issuecomment-1000949678

2021-12-25 00:24 UTC, shwestrick commented on src/base/PrettySimpleDoc.sml
> +        | Rigid d => (false, Rigid d, 0 (* TODO *), false)
This looks like an okay hack to me; using size 0 will cause the layout engine to prefer this layout.

Although, perhaps more "correct" would be to still do the loop over `d` and then override the size, giving it a huge size so that the layout engine ignores the flattened layout.

2021-12-25 00:24 UTC, shwestrick commented on src/pretty-print/PrettySig.sml
> +        | _                 =>
In these cases, perhaps we could not align the `=>`? Just to be consistent with the rest of the file.

2021-12-25 01:03 UTC, HarrisonGrodin commented
Think I addressed the issues you mentioned - does this look better/mergeable now?

2021-12-25 01:17 UTC, HarrisonGrodin commented
Actually, not sure `Rigid` is behaving how I would expect it to. If I make `sig ... end` blocks not be rigid but force `type` specs to be rigid, I would expect
```sml
sig type t end
```
to stay as-is and
```sml
sig type t and u end
```
to be broken onto multiple lines. However, it seems that this breaks both examples onto multiple lines?

2021-12-25 01:24 UTC, shwestrick approved these changes

2021-12-25 01:25 UTC, shwestrick commented
Both `type t` and `type t and u` are handled by the same AST node, so it makes sense that whatever the formatting is for one would also be used for the other.

2021-12-25 01:26 UTC, shwestrick commented
I.e. that behavior makes sense to me: type specs are rigid, so both the snippets you showed should be ungrouped.

2021-12-25 04:13 UTC, HarrisonGrodin commented
Hmm... I was thinking that if type specs are rigid, they could be grouped "as a whole", but the grouping wouldn't go underneath the rigid boundary. So, if `type t` is rigid, it could stay in a single line `sig type t end` (since no flattening of `type t` itself would occur), but `type t and u` would take up multiple lines/not be flattenable, causing a multiline `sig`.

2021-12-25 14:55 UTC, shwestrick commented
Oh, it just occurred to me that the hack of using size 0 for rigid docs (in the layout engine) is not correct. It's possible this is contributing to the strange behavior. The sizes of flattened docs need to be true sizes, because these are used to efficiently determine sizes of outer flattened docs (see code snippet):

https://github.com/shwestrick/parse-sml/blob/45870361a1f0f534e9baee18e3b5bbe11795821a/src/base/PrettySimpleDoc.sml#L148-L161

To fix it, in `PrettySimpleDoc`, we could change `flatten` to have type `doc -> ... option`, where NONE means *not flattenable*, due to rigidity of a subcomponent. Then the definition of `group` would case on the result and, in the NONE case, not introduce a `Choice` at all.

Thoughts?

2021-12-25 21:25 UTC, merged